### ISSUE TITLE
More explanations on the maths

### ISSUE THREAD

**Issue by Heshyo** [drmpeg/gr-paint#13]
I understand each pixel of the image will correspond to an intensity, and you send each line of the image over a specific amount of time, so that the receiver will have time to actually see.

What I don't understand is how to go from one array containing the pixel of one line into corresponding IQs. I feel there's also a need to adjust things to avoid issues when repeating a line or transmitting a new one.

Would you care explaining a bit the process? I checked the code, as well as the one from https://github.com/polygon/spectrum_painter but I couldn't really get much.

**Comment by drmpeg** [comment]
The inverse FFT (on line 179) transforms the pixel domain into the frequency domain. A line is always 4096 pixels (the size of the inverse FFT), with pixel 0 equal to (center frequency - 1 MHz) and pixel 4095 equal to (center frequency + 1 MHz).
