### ISSUE TITLE
Not compatible with GNU Radio 3.8.1.0

### ISSUE THREAD

**Issue by cheapskate-mj12** [drmpeg/gr-paint#15]
Tried to add to fresh install of Ubuntu 20.04 with GR 3.8.1.0, when I run
make ..
I get

CMake Error at CMakeLists.txt:143 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.7.6".
  The following configuration files were considered but not accepted:
    /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.1.0
    /lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.1.0
-- Configuring incomplete, errors occurred!

**Comment by drmpeg** [comment]
Give this a try.

https://github.com/drmpeg/gr-paint38

**Comment by cheapskate-mj12** [comment]
Tried my own flowgraph and your example flowgraph with same result - 
Gnu radio 3.8.1.0 returns /gr-paint38/apps/paint_tx.py, 
line 39 in <module>Import paintModule not found error: no module named paint

Conversion to python3 problem? I need a prerequisite?

**Comment by cheapskate-mj12** [comment]
I forgot to tell you, running with a b200mini, and thanks so much for the help!

**Comment by drmpeg** [comment]
You have to install OOT's into the same directory you've installed GNU Radio. If you installed GNU Radio with apt-get, that will be /usr. You can check with gnuradio-config --prefix. To install into the correct directory, you need to use -DCMAKE_INSTALL_PREFIX during the cmake phase of the build.

cmake -DCMAKE_INSTALL_PREFIX=/usr ../

To make sure things go smoothly, delete the contents of your build directory. Like so:

cd gr-paint38/build
rm -rf *
cmake -DCMAKE_INSTALL_PREFIX=/usr ../
make
sudo make install
sudo ldconfig

**Comment by cheapskate-mj12** [comment]
Got it! Thank you. I can see fiona...
