### ISSUE TITLE
cmake warnings

### ISSUE THREAD

**Issue by ZeroChaos-** [drmpeg/gr-paint#2]
CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "gnuradio-paint".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  python/CMakeLists.txt:44 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "/usr/bin/python2.7".
Call Stack (most recent call first):
  python/CMakeLists.txt:44 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/lib64/cmake/gnuradio/GrTest.cmake:45 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target
  "/var/tmp/portage/net-wireless/gr-paint-9999/work/gr-paint-9999/python/qa_paint_bc.py".
Call Stack (most recent call first):
  python/CMakeLists.txt:44 (GR_ADD_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by drmpeg** [comment]
I believe all these warnings are a function of using a cmake version >= 3. With cmake version 2.8.11.2 (in use here), there are no warnings. This is really a GNU Radio issue, since all the cmake files were generated with gr_modtool.

**Comment by ZeroChaos-** [comment]
confirmed, I am on cmake 3.2.2

Looks like this is the upstream bug https://gnuradio.org/redmine/issues/785

**Comment by ZeroChaos-** [comment]
long long obsolete
